Traceback (most recent call last):
  File "/Users/peanutcookie/anaconda3/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/peanutcookie/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/peanutcookie/anaconda3/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/peanutcookie/anaconda3/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/peanutcookie/anaconda3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/peanutcookie/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/peanutcookie/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/peanutcookie/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Dropping missing values
df.dropna(subset = ["product_name"], axis=1)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
Cell [0;32mIn[16], line 2[0m
[1;32m      1[0m [38;5;66;03m# Dropping missing values[39;00m
[0;32m----> 2[0m [43mdf[49m[38;5;241;43m.[39;49m[43mdropna[49m[43m([49m[43msubset[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[43m[[49m[38;5;124;43m"[39;49m[38;5;124;43mproduct_name[39;49m[38;5;124;43m"[39;49m[43m][49m[43m,[49m[43m [49m[43maxis[49m[38;5;241;43m=[39;49m[38;5;241;43m1[39;49m[43m)[49m

File [0;32m~/anaconda3/lib/python3.10/site-packages/pandas/util/_decorators.py:331[0m, in [0;36mdeprecate_nonkeyword_arguments.<locals>.decorate.<locals>.wrapper[0;34m(*args, **kwargs)[0m
[1;32m    325[0m [38;5;28;01mif[39;00m [38;5;28mlen[39m(args) [38;5;241m>[39m num_allow_args:
[1;32m    326[0m     warnings[38;5;241m.[39mwarn(
[1;32m    327[0m         msg[38;5;241m.[39mformat(arguments[38;5;241m=[39m_format_argument_list(allow_args)),
[1;32m    328[0m         [38;5;167;01mFutureWarning[39;00m,
[1;32m    329[0m         stacklevel[38;5;241m=[39mfind_stack_level(),
[1;32m    330[0m     )
[0;32m--> 331[0m [38;5;28;01mreturn[39;00m [43mfunc[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m~/anaconda3/lib/python3.10/site-packages/pandas/core/frame.py:6561[0m, in [0;36mDataFrame.dropna[0;34m(self, axis, how, thresh, subset, inplace)[0m
[1;32m   6559[0m     check [38;5;241m=[39m indices [38;5;241m==[39m [38;5;241m-[39m[38;5;241m1[39m
[1;32m   6560[0m     [38;5;28;01mif[39;00m check[38;5;241m.[39many():
[0;32m-> 6561[0m         [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m(np[38;5;241m.[39marray(subset)[check][38;5;241m.[39mtolist())
[1;32m   6562[0m     agg_obj [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mtake(indices, axis[38;5;241m=[39magg_axis)
[1;32m   6564[0m [38;5;28;01mif[39;00m thresh [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m no_default:

[0;31mKeyError[0m: ['product_name']
KeyError: ['product_name']

